### ISSUE TITLE
TODO List

### ISSUE THREAD

**Issue by mymedia2** [mymedia2/PythonWinter2015-TPG#1]
# Что нужно сделать
- [ ] расширить параметры командной строки
- [ ] при запуске из файла корректно указывать номер строки, где произошла ошибка
- [x] добавить проверки при перемножении матриц и сложении векторов
- [x] исправить умножение числа на матрицу
- [x] сделать отрицательные числа
- [x] посмотреть, что получается при комбинировании матриц и векторов
- [ ] добавить возможность вводить матрицу на нескольких строках
  - [ ] ...

**Comment by mymedia2** [comment]
- [ ] возможность выводить строчки из скрипта
